#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SendScheduleFinals
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EnrollmentDatabase")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InserttblEmployee(tblEmployee instance);
    partial void UpdatetblEmployee(tblEmployee instance);
    partial void DeletetblEmployee(tblEmployee instance);
    partial void InserttblGradeLevel(tblGradeLevel instance);
    partial void UpdatetblGradeLevel(tblGradeLevel instance);
    partial void DeletetblGradeLevel(tblGradeLevel instance);
    partial void InserttblRecord(tblRecord instance);
    partial void UpdatetblRecord(tblRecord instance);
    partial void DeletetblRecord(tblRecord instance);
    partial void InserttblSchedule(tblSchedule instance);
    partial void UpdatetblSchedule(tblSchedule instance);
    partial void DeletetblSchedule(tblSchedule instance);
    partial void InserttblStudent(tblStudent instance);
    partial void UpdatetblStudent(tblStudent instance);
    partial void DeletetblStudent(tblStudent instance);
    partial void InserttblStudentSchedule(tblStudentSchedule instance);
    partial void UpdatetblStudentSchedule(tblStudentSchedule instance);
    partial void DeletetblStudentSchedule(tblStudentSchedule instance);
    partial void InserttblSubject(tblSubject instance);
    partial void UpdatetblSubject(tblSubject instance);
    partial void DeletetblSubject(tblSubject instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::SendScheduleFinals.Properties.Settings.Default.EnrollmentDatabaseConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblEmployee> tblEmployees
		{
			get
			{
				return this.GetTable<tblEmployee>();
			}
		}
		
		public System.Data.Linq.Table<tblGradeLevel> tblGradeLevels
		{
			get
			{
				return this.GetTable<tblGradeLevel>();
			}
		}
		
		public System.Data.Linq.Table<tblRecord> tblRecords
		{
			get
			{
				return this.GetTable<tblRecord>();
			}
		}
		
		public System.Data.Linq.Table<tblSchedule> tblSchedules
		{
			get
			{
				return this.GetTable<tblSchedule>();
			}
		}
		
		public System.Data.Linq.Table<tblStudent> tblStudents
		{
			get
			{
				return this.GetTable<tblStudent>();
			}
		}
		
		public System.Data.Linq.Table<tblStudentSchedule> tblStudentSchedules
		{
			get
			{
				return this.GetTable<tblStudentSchedule>();
			}
		}
		
		public System.Data.Linq.Table<tblSubject> tblSubjects
		{
			get
			{
				return this.GetTable<tblSubject>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblEmployee")]
	public partial class tblEmployee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _employeeID;
		
		private string _employeeName;
		
		private string _classification;
		
		private string _employeeEmail;
		
		private string _employeePass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnemployeeIDChanging(int value);
    partial void OnemployeeIDChanged();
    partial void OnemployeeNameChanging(string value);
    partial void OnemployeeNameChanged();
    partial void OnclassificationChanging(string value);
    partial void OnclassificationChanged();
    partial void OnemployeeEmailChanging(string value);
    partial void OnemployeeEmailChanged();
    partial void OnemployeePassChanging(string value);
    partial void OnemployeePassChanged();
    #endregion
		
		public tblEmployee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeeID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int employeeID
		{
			get
			{
				return this._employeeID;
			}
			set
			{
				if ((this._employeeID != value))
				{
					this.OnemployeeIDChanging(value);
					this.SendPropertyChanging();
					this._employeeID = value;
					this.SendPropertyChanged("employeeID");
					this.OnemployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeeName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string employeeName
		{
			get
			{
				return this._employeeName;
			}
			set
			{
				if ((this._employeeName != value))
				{
					this.OnemployeeNameChanging(value);
					this.SendPropertyChanging();
					this._employeeName = value;
					this.SendPropertyChanged("employeeName");
					this.OnemployeeNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_classification", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string classification
		{
			get
			{
				return this._classification;
			}
			set
			{
				if ((this._classification != value))
				{
					this.OnclassificationChanging(value);
					this.SendPropertyChanging();
					this._classification = value;
					this.SendPropertyChanged("classification");
					this.OnclassificationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeeEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string employeeEmail
		{
			get
			{
				return this._employeeEmail;
			}
			set
			{
				if ((this._employeeEmail != value))
				{
					this.OnemployeeEmailChanging(value);
					this.SendPropertyChanging();
					this._employeeEmail = value;
					this.SendPropertyChanged("employeeEmail");
					this.OnemployeeEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeePass", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string employeePass
		{
			get
			{
				return this._employeePass;
			}
			set
			{
				if ((this._employeePass != value))
				{
					this.OnemployeePassChanging(value);
					this.SendPropertyChanging();
					this._employeePass = value;
					this.SendPropertyChanged("employeePass");
					this.OnemployeePassChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblGradeLevel")]
	public partial class tblGradeLevel : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _gradeLevelID;
		
		private int _gradeLevel;
		
		private string _strand;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OngradeLevelIDChanging(int value);
    partial void OngradeLevelIDChanged();
    partial void OngradeLevelChanging(int value);
    partial void OngradeLevelChanged();
    partial void OnstrandChanging(string value);
    partial void OnstrandChanged();
    #endregion
		
		public tblGradeLevel()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradeLevelID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int gradeLevelID
		{
			get
			{
				return this._gradeLevelID;
			}
			set
			{
				if ((this._gradeLevelID != value))
				{
					this.OngradeLevelIDChanging(value);
					this.SendPropertyChanging();
					this._gradeLevelID = value;
					this.SendPropertyChanged("gradeLevelID");
					this.OngradeLevelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradeLevel", DbType="Int NOT NULL")]
		public int gradeLevel
		{
			get
			{
				return this._gradeLevel;
			}
			set
			{
				if ((this._gradeLevel != value))
				{
					this.OngradeLevelChanging(value);
					this.SendPropertyChanging();
					this._gradeLevel = value;
					this.SendPropertyChanged("gradeLevel");
					this.OngradeLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_strand", DbType="NVarChar(50)")]
		public string strand
		{
			get
			{
				return this._strand;
			}
			set
			{
				if ((this._strand != value))
				{
					this.OnstrandChanging(value);
					this.SendPropertyChanging();
					this._strand = value;
					this.SendPropertyChanged("strand");
					this.OnstrandChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblRecord")]
	public partial class tblRecord : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _recordID;
		
		private int _studentID;
		
		private string _schoolName;
		
		private string _schoolYear;
		
		private int _schoolTerm;
		
		private string _subject;
		
		private int _grade;
		
		private string _gradeStatus;
		
		private EntityRef<tblStudent> _tblStudent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnrecordIDChanging(int value);
    partial void OnrecordIDChanged();
    partial void OnstudentIDChanging(int value);
    partial void OnstudentIDChanged();
    partial void OnschoolNameChanging(string value);
    partial void OnschoolNameChanged();
    partial void OnschoolYearChanging(string value);
    partial void OnschoolYearChanged();
    partial void OnschoolTermChanging(int value);
    partial void OnschoolTermChanged();
    partial void OnsubjectChanging(string value);
    partial void OnsubjectChanged();
    partial void OngradeChanging(int value);
    partial void OngradeChanged();
    partial void OngradeStatusChanging(string value);
    partial void OngradeStatusChanged();
    #endregion
		
		public tblRecord()
		{
			this._tblStudent = default(EntityRef<tblStudent>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_recordID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int recordID
		{
			get
			{
				return this._recordID;
			}
			set
			{
				if ((this._recordID != value))
				{
					this.OnrecordIDChanging(value);
					this.SendPropertyChanging();
					this._recordID = value;
					this.SendPropertyChanged("recordID");
					this.OnrecordIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentID", DbType="Int NOT NULL")]
		public int studentID
		{
			get
			{
				return this._studentID;
			}
			set
			{
				if ((this._studentID != value))
				{
					if (this._tblStudent.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstudentIDChanging(value);
					this.SendPropertyChanging();
					this._studentID = value;
					this.SendPropertyChanged("studentID");
					this.OnstudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schoolName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string schoolName
		{
			get
			{
				return this._schoolName;
			}
			set
			{
				if ((this._schoolName != value))
				{
					this.OnschoolNameChanging(value);
					this.SendPropertyChanging();
					this._schoolName = value;
					this.SendPropertyChanged("schoolName");
					this.OnschoolNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schoolYear", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string schoolYear
		{
			get
			{
				return this._schoolYear;
			}
			set
			{
				if ((this._schoolYear != value))
				{
					this.OnschoolYearChanging(value);
					this.SendPropertyChanging();
					this._schoolYear = value;
					this.SendPropertyChanged("schoolYear");
					this.OnschoolYearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_schoolTerm", DbType="Int NOT NULL")]
		public int schoolTerm
		{
			get
			{
				return this._schoolTerm;
			}
			set
			{
				if ((this._schoolTerm != value))
				{
					this.OnschoolTermChanging(value);
					this.SendPropertyChanging();
					this._schoolTerm = value;
					this.SendPropertyChanged("schoolTerm");
					this.OnschoolTermChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subject", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string subject
		{
			get
			{
				return this._subject;
			}
			set
			{
				if ((this._subject != value))
				{
					this.OnsubjectChanging(value);
					this.SendPropertyChanging();
					this._subject = value;
					this.SendPropertyChanged("subject");
					this.OnsubjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grade", DbType="Int NOT NULL")]
		public int grade
		{
			get
			{
				return this._grade;
			}
			set
			{
				if ((this._grade != value))
				{
					this.OngradeChanging(value);
					this.SendPropertyChanging();
					this._grade = value;
					this.SendPropertyChanged("grade");
					this.OngradeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradeStatus", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string gradeStatus
		{
			get
			{
				return this._gradeStatus;
			}
			set
			{
				if ((this._gradeStatus != value))
				{
					this.OngradeStatusChanging(value);
					this.SendPropertyChanging();
					this._gradeStatus = value;
					this.SendPropertyChanged("gradeStatus");
					this.OngradeStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblStudent_tblRecord", Storage="_tblStudent", ThisKey="studentID", OtherKey="StudentID", IsForeignKey=true)]
		public tblStudent tblStudent
		{
			get
			{
				return this._tblStudent.Entity;
			}
			set
			{
				tblStudent previousValue = this._tblStudent.Entity;
				if (((previousValue != value) 
							|| (this._tblStudent.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblStudent.Entity = null;
						previousValue.tblRecords.Remove(this);
					}
					this._tblStudent.Entity = value;
					if ((value != null))
					{
						value.tblRecords.Add(this);
						this._studentID = value.StudentID;
					}
					else
					{
						this._studentID = default(int);
					}
					this.SendPropertyChanged("tblStudent");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSchedule")]
	public partial class tblSchedule : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ScheduleID;
		
		private string _ClassPeriod;
		
		private string _ClassDay;
		
		private System.Nullable<int> _subjectID;
		
		private System.Nullable<int> _employeeID;
		
		private System.Nullable<int> _gradeLevelID;
		
		private string _section;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnScheduleIDChanging(int value);
    partial void OnScheduleIDChanged();
    partial void OnClassPeriodChanging(string value);
    partial void OnClassPeriodChanged();
    partial void OnClassDayChanging(string value);
    partial void OnClassDayChanged();
    partial void OnsubjectIDChanging(System.Nullable<int> value);
    partial void OnsubjectIDChanged();
    partial void OnemployeeIDChanging(System.Nullable<int> value);
    partial void OnemployeeIDChanged();
    partial void OngradeLevelIDChanging(System.Nullable<int> value);
    partial void OngradeLevelIDChanged();
    partial void OnsectionChanging(string value);
    partial void OnsectionChanged();
    #endregion
		
		public tblSchedule()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ScheduleID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ScheduleID
		{
			get
			{
				return this._ScheduleID;
			}
			set
			{
				if ((this._ScheduleID != value))
				{
					this.OnScheduleIDChanging(value);
					this.SendPropertyChanging();
					this._ScheduleID = value;
					this.SendPropertyChanged("ScheduleID");
					this.OnScheduleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassPeriod", DbType="NVarChar(50)")]
		public string ClassPeriod
		{
			get
			{
				return this._ClassPeriod;
			}
			set
			{
				if ((this._ClassPeriod != value))
				{
					this.OnClassPeriodChanging(value);
					this.SendPropertyChanging();
					this._ClassPeriod = value;
					this.SendPropertyChanged("ClassPeriod");
					this.OnClassPeriodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ClassDay", DbType="NVarChar(50)")]
		public string ClassDay
		{
			get
			{
				return this._ClassDay;
			}
			set
			{
				if ((this._ClassDay != value))
				{
					this.OnClassDayChanging(value);
					this.SendPropertyChanging();
					this._ClassDay = value;
					this.SendPropertyChanged("ClassDay");
					this.OnClassDayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subjectID", DbType="Int")]
		public System.Nullable<int> subjectID
		{
			get
			{
				return this._subjectID;
			}
			set
			{
				if ((this._subjectID != value))
				{
					this.OnsubjectIDChanging(value);
					this.SendPropertyChanging();
					this._subjectID = value;
					this.SendPropertyChanged("subjectID");
					this.OnsubjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_employeeID", DbType="Int")]
		public System.Nullable<int> employeeID
		{
			get
			{
				return this._employeeID;
			}
			set
			{
				if ((this._employeeID != value))
				{
					this.OnemployeeIDChanging(value);
					this.SendPropertyChanging();
					this._employeeID = value;
					this.SendPropertyChanged("employeeID");
					this.OnemployeeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gradeLevelID", DbType="Int")]
		public System.Nullable<int> gradeLevelID
		{
			get
			{
				return this._gradeLevelID;
			}
			set
			{
				if ((this._gradeLevelID != value))
				{
					this.OngradeLevelIDChanging(value);
					this.SendPropertyChanging();
					this._gradeLevelID = value;
					this.SendPropertyChanged("gradeLevelID");
					this.OngradeLevelIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_section", DbType="NVarChar(50)")]
		public string section
		{
			get
			{
				return this._section;
			}
			set
			{
				if ((this._section != value))
				{
					this.OnsectionChanging(value);
					this.SendPropertyChanging();
					this._section = value;
					this.SendPropertyChanged("section");
					this.OnsectionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblStudent")]
	public partial class tblStudent : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _StudentID;
		
		private string _studentName;
		
		private string _studentGradeLevel;
		
		private int _studentContactNumber;
		
		private string _studentEmail;
		
		private string _studentAddress;
		
		private System.DateTime _studentDateOfBirth;
		
		private string _studentImage;
		
		private int _studentAge;
		
		private string _studentGender;
		
		private string _studentNationality;
		
		private string _studentStatus;
		
		private string _paymentPlan;
		
		private EntitySet<tblRecord> _tblRecords;
		
		private EntitySet<tblStudentSchedule> _tblStudentSchedules;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnStudentIDChanging(int value);
    partial void OnStudentIDChanged();
    partial void OnstudentNameChanging(string value);
    partial void OnstudentNameChanged();
    partial void OnstudentGradeLevelChanging(string value);
    partial void OnstudentGradeLevelChanged();
    partial void OnstudentContactNumberChanging(int value);
    partial void OnstudentContactNumberChanged();
    partial void OnstudentEmailChanging(string value);
    partial void OnstudentEmailChanged();
    partial void OnstudentAddressChanging(string value);
    partial void OnstudentAddressChanged();
    partial void OnstudentDateOfBirthChanging(System.DateTime value);
    partial void OnstudentDateOfBirthChanged();
    partial void OnstudentImageChanging(string value);
    partial void OnstudentImageChanged();
    partial void OnstudentAgeChanging(int value);
    partial void OnstudentAgeChanged();
    partial void OnstudentGenderChanging(string value);
    partial void OnstudentGenderChanged();
    partial void OnstudentNationalityChanging(string value);
    partial void OnstudentNationalityChanged();
    partial void OnstudentStatusChanging(string value);
    partial void OnstudentStatusChanged();
    partial void OnpaymentPlanChanging(string value);
    partial void OnpaymentPlanChanged();
    #endregion
		
		public tblStudent()
		{
			this._tblRecords = new EntitySet<tblRecord>(new Action<tblRecord>(this.attach_tblRecords), new Action<tblRecord>(this.detach_tblRecords));
			this._tblStudentSchedules = new EntitySet<tblStudentSchedule>(new Action<tblStudentSchedule>(this.attach_tblStudentSchedules), new Action<tblStudentSchedule>(this.detach_tblStudentSchedules));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int StudentID
		{
			get
			{
				return this._StudentID;
			}
			set
			{
				if ((this._StudentID != value))
				{
					this.OnStudentIDChanging(value);
					this.SendPropertyChanging();
					this._StudentID = value;
					this.SendPropertyChanged("StudentID");
					this.OnStudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string studentName
		{
			get
			{
				return this._studentName;
			}
			set
			{
				if ((this._studentName != value))
				{
					this.OnstudentNameChanging(value);
					this.SendPropertyChanging();
					this._studentName = value;
					this.SendPropertyChanged("studentName");
					this.OnstudentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentGradeLevel", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string studentGradeLevel
		{
			get
			{
				return this._studentGradeLevel;
			}
			set
			{
				if ((this._studentGradeLevel != value))
				{
					this.OnstudentGradeLevelChanging(value);
					this.SendPropertyChanging();
					this._studentGradeLevel = value;
					this.SendPropertyChanged("studentGradeLevel");
					this.OnstudentGradeLevelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentContactNumber", DbType="Int NOT NULL")]
		public int studentContactNumber
		{
			get
			{
				return this._studentContactNumber;
			}
			set
			{
				if ((this._studentContactNumber != value))
				{
					this.OnstudentContactNumberChanging(value);
					this.SendPropertyChanging();
					this._studentContactNumber = value;
					this.SendPropertyChanged("studentContactNumber");
					this.OnstudentContactNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentEmail", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string studentEmail
		{
			get
			{
				return this._studentEmail;
			}
			set
			{
				if ((this._studentEmail != value))
				{
					this.OnstudentEmailChanging(value);
					this.SendPropertyChanging();
					this._studentEmail = value;
					this.SendPropertyChanged("studentEmail");
					this.OnstudentEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentAddress", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string studentAddress
		{
			get
			{
				return this._studentAddress;
			}
			set
			{
				if ((this._studentAddress != value))
				{
					this.OnstudentAddressChanging(value);
					this.SendPropertyChanging();
					this._studentAddress = value;
					this.SendPropertyChanged("studentAddress");
					this.OnstudentAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentDateOfBirth", DbType="Date NOT NULL")]
		public System.DateTime studentDateOfBirth
		{
			get
			{
				return this._studentDateOfBirth;
			}
			set
			{
				if ((this._studentDateOfBirth != value))
				{
					this.OnstudentDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._studentDateOfBirth = value;
					this.SendPropertyChanged("studentDateOfBirth");
					this.OnstudentDateOfBirthChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentImage", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string studentImage
		{
			get
			{
				return this._studentImage;
			}
			set
			{
				if ((this._studentImage != value))
				{
					this.OnstudentImageChanging(value);
					this.SendPropertyChanging();
					this._studentImage = value;
					this.SendPropertyChanged("studentImage");
					this.OnstudentImageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentAge", DbType="Int NOT NULL")]
		public int studentAge
		{
			get
			{
				return this._studentAge;
			}
			set
			{
				if ((this._studentAge != value))
				{
					this.OnstudentAgeChanging(value);
					this.SendPropertyChanging();
					this._studentAge = value;
					this.SendPropertyChanged("studentAge");
					this.OnstudentAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentGender", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string studentGender
		{
			get
			{
				return this._studentGender;
			}
			set
			{
				if ((this._studentGender != value))
				{
					this.OnstudentGenderChanging(value);
					this.SendPropertyChanging();
					this._studentGender = value;
					this.SendPropertyChanged("studentGender");
					this.OnstudentGenderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentNationality", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string studentNationality
		{
			get
			{
				return this._studentNationality;
			}
			set
			{
				if ((this._studentNationality != value))
				{
					this.OnstudentNationalityChanging(value);
					this.SendPropertyChanging();
					this._studentNationality = value;
					this.SendPropertyChanged("studentNationality");
					this.OnstudentNationalityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentStatus", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string studentStatus
		{
			get
			{
				return this._studentStatus;
			}
			set
			{
				if ((this._studentStatus != value))
				{
					this.OnstudentStatusChanging(value);
					this.SendPropertyChanging();
					this._studentStatus = value;
					this.SendPropertyChanged("studentStatus");
					this.OnstudentStatusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_paymentPlan", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string paymentPlan
		{
			get
			{
				return this._paymentPlan;
			}
			set
			{
				if ((this._paymentPlan != value))
				{
					this.OnpaymentPlanChanging(value);
					this.SendPropertyChanging();
					this._paymentPlan = value;
					this.SendPropertyChanged("paymentPlan");
					this.OnpaymentPlanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblStudent_tblRecord", Storage="_tblRecords", ThisKey="StudentID", OtherKey="studentID")]
		public EntitySet<tblRecord> tblRecords
		{
			get
			{
				return this._tblRecords;
			}
			set
			{
				this._tblRecords.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblStudent_tblStudentSchedule", Storage="_tblStudentSchedules", ThisKey="StudentID", OtherKey="studentID")]
		public EntitySet<tblStudentSchedule> tblStudentSchedules
		{
			get
			{
				return this._tblStudentSchedules;
			}
			set
			{
				this._tblStudentSchedules.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblRecords(tblRecord entity)
		{
			this.SendPropertyChanging();
			entity.tblStudent = this;
		}
		
		private void detach_tblRecords(tblRecord entity)
		{
			this.SendPropertyChanging();
			entity.tblStudent = null;
		}
		
		private void attach_tblStudentSchedules(tblStudentSchedule entity)
		{
			this.SendPropertyChanging();
			entity.tblStudent = this;
		}
		
		private void detach_tblStudentSchedules(tblStudentSchedule entity)
		{
			this.SendPropertyChanging();
			entity.tblStudent = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblStudentSchedule")]
	public partial class tblStudentSchedule : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _studentScheduleID;
		
		private int _studentID;
		
		private int _scheduleID;
		
		private EntityRef<tblStudent> _tblStudent;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnstudentScheduleIDChanging(int value);
    partial void OnstudentScheduleIDChanged();
    partial void OnstudentIDChanging(int value);
    partial void OnstudentIDChanged();
    partial void OnscheduleIDChanging(int value);
    partial void OnscheduleIDChanged();
    #endregion
		
		public tblStudentSchedule()
		{
			this._tblStudent = default(EntityRef<tblStudent>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentScheduleID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int studentScheduleID
		{
			get
			{
				return this._studentScheduleID;
			}
			set
			{
				if ((this._studentScheduleID != value))
				{
					this.OnstudentScheduleIDChanging(value);
					this.SendPropertyChanging();
					this._studentScheduleID = value;
					this.SendPropertyChanged("studentScheduleID");
					this.OnstudentScheduleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_studentID", DbType="Int NOT NULL")]
		public int studentID
		{
			get
			{
				return this._studentID;
			}
			set
			{
				if ((this._studentID != value))
				{
					if (this._tblStudent.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnstudentIDChanging(value);
					this.SendPropertyChanging();
					this._studentID = value;
					this.SendPropertyChanged("studentID");
					this.OnstudentIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_scheduleID", DbType="Int NOT NULL")]
		public int scheduleID
		{
			get
			{
				return this._scheduleID;
			}
			set
			{
				if ((this._scheduleID != value))
				{
					this.OnscheduleIDChanging(value);
					this.SendPropertyChanging();
					this._scheduleID = value;
					this.SendPropertyChanged("scheduleID");
					this.OnscheduleIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblStudent_tblStudentSchedule", Storage="_tblStudent", ThisKey="studentID", OtherKey="StudentID", IsForeignKey=true)]
		public tblStudent tblStudent
		{
			get
			{
				return this._tblStudent.Entity;
			}
			set
			{
				tblStudent previousValue = this._tblStudent.Entity;
				if (((previousValue != value) 
							|| (this._tblStudent.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblStudent.Entity = null;
						previousValue.tblStudentSchedules.Remove(this);
					}
					this._tblStudent.Entity = value;
					if ((value != null))
					{
						value.tblStudentSchedules.Add(this);
						this._studentID = value.StudentID;
					}
					else
					{
						this._studentID = default(int);
					}
					this.SendPropertyChanged("tblStudent");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSubject")]
	public partial class tblSubject : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _subjectID;
		
		private string _subjectName;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnsubjectIDChanging(int value);
    partial void OnsubjectIDChanged();
    partial void OnsubjectNameChanging(string value);
    partial void OnsubjectNameChanged();
    #endregion
		
		public tblSubject()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subjectID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int subjectID
		{
			get
			{
				return this._subjectID;
			}
			set
			{
				if ((this._subjectID != value))
				{
					this.OnsubjectIDChanging(value);
					this.SendPropertyChanging();
					this._subjectID = value;
					this.SendPropertyChanged("subjectID");
					this.OnsubjectIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subjectName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string subjectName
		{
			get
			{
				return this._subjectName;
			}
			set
			{
				if ((this._subjectName != value))
				{
					this.OnsubjectNameChanging(value);
					this.SendPropertyChanging();
					this._subjectName = value;
					this.SendPropertyChanged("subjectName");
					this.OnsubjectNameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
